### ISSUE TITLE
Park search and completion

### ISSUE THREAD

**Issue by Masynchin** [bogdano/pick-a-park#3]
Hello, ~~Borgan~~ Bogdan!

I came across to your repo while searching for HTMX examples on input suggestions. In your site I can type something and have completions for it. But how it is done? I am unable to find `<input>` element for the search from the site index in your source code. Can you explain how it is done?

**Comment by bogdano** [comment]
Hey there!

That's actually not handled by my code; it's a Mapbox Geocoder element. The Geocoder uses Mapbox's JS script to display results, and when you pick one then an htmx.ajax request is sent to the server along with the name of the place chosen and the coordinates of the user. This starts at line 127 in index.templ.

An HTMX `<input>` which searches your own data for suggestions should probably use a hx-trigger on keydown, with a delay, and some staggering to prevent too many quick consecutive requests.

**Comment by Masynchin** [comment]
> An HTMX `<input>` which searches your own data for suggestions should probably use a hx-trigger on keydown, with a delay, and some staggering to prevent too many quick consecutive requests.

Yep, it is how I done it, but my version utilizes "datalist"-API that is not really works in Safari, unlike yours, which handles Safari perfectly.

> ... and when you pick one then an htmx.ajax request is sent to the server along with the name of the place chosen and the coordinates of the user. This starts at line 127 in index.templ.

Thanks a lot! And sorry for the typo, Богдан :) Good luck with your project!
